force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <label>Expense</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Housing</fullName>
                <default>true</default>
                <label>Housing</label>
            </value>
            <value>
                <fullName>Transportation</fullName>
            </value>
            <value>
                <fullName>Food</fullName>
            </value>
            <value>
                <fullName>Medical Healthcare</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Is_Recurrent__c.field-meta.xml
<CustomField>
    <fullName>Is_Recurrent__c</fullName>
    <formula>NOT(
				ISBLANK(
								TEXT(Recurrence_Periodicity__c)
				)
)</formula>
    <label>Is Recurrent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Recurrence_Periodicity__c.field-meta.xml
<CustomField>
    <fullName>Recurrence_Periodicity__c</fullName>
    <label>Recurrence Periodicity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ExpenseController.cls
public with sharing class ExpenseController {

    @AuraEnabled(cacheable=true)
    public static List<Expense__c> getExpenseList() {

        return [SELECT Id, Name, Amount__c, Category__c, Expense_Date__c
                        , Is_Recurrent__c
                        , Recurrence_Periodicity__c
                    FROM Expense__c];
    }

    @AuraEnabled
    public static void updateExpenses(Object data) {
        List<Expense__c> expensesToUpdate = (List<Expense__c>) JSON.deserialize(
            JSON.serialize(data),
            List<Expense__c>.class
        );
        update expensesToUpdate;
    }

    @AuraEnabled(cacheable=true)
    public static List<DataSet> getExpensesByMonth(Integer month){

        List<AggregateResult> result = [SELECT SUM(Amount__c) Total, Category__c
                                            FROM Expense__c
                                            WHERE CALENDAR_MONTH(Expense_Date__c) = :month
                                            GROUP BY Category__c];

        List<DataSet> dataSet = new List<DataSet>();

        for(AggregateResult ar:result){
            String category = (String)ar.get('Category__c') ;
            Decimal total = (Decimal)ar.get('Total');
            dataSet.add(new DataSet(category, total));
        }
        return dataSet;
    }

    public class DataSet {

        public DataSet(String label, Decimal total){
            this.label  = label;
            this.total = total;
        }

        @AuraEnabled
        public String label {get;set;}

        @AuraEnabled
        public Decimal  total {get;set;}
    }
}