force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <label>Expense</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Housing</fullName>
                <default>true</default>
                <label>Housing</label>
            </value>
            <value>
                <fullName>Transportation</fullName>
            </value>
            <value>
                <fullName>Food</fullName>
            </value>
            <value>
                <fullName>Medical Healthcare</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expense__c/fields/No_Recurrences__c.field-meta.xml
<CustomField>
    <fullName>No_Recurrences__c</fullName>
    <label>No of Recurrences</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Recurrence_Periodicity__c.field-meta.xml
<CustomField>
    <fullName>Recurrence_Periodicity__c</fullName>
    <label>Recurrence Periodicity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestUtils.cls
@isTest
public class TestUtils {

    public static Expense__c buildExpense(){
        return buildExpense(null, null, null, null, null);
    }

    public static Expense__c buildExpense(String name, String category, Decimal amount, String rePeriodicity, Integer noRecurrence){

        if (String.isBlank(name)) {
            name = 'Expense';
        }
        if (String.isBlank(category)) {
            category = 'Food';
        }
        if (amount == null) {
            amount = 10.5;
        }
        if (String.isBlank(rePeriodicity)) {
            rePeriodicity = 'Monthly';
        }
        if (noRecurrence == null) {
            noRecurrence = 12;
        }

        Expense__c expense = new Expense__c(
            Name = name,
            Category__c = category,
            Amount__c = amount,
            Recurrence_Periodicity__c = rePeriodicity,
            No_Recurrences__c = noRecurrence
        );

        return expense;
    }
}